Updated action to support adding optional environment variables and secrets
robusta-dev/prometheus-remediation pull request #1
Opened 2023-12-19 09:39 UTC by pavangudiwada

Sample
![image](https://github.com/robusta-dev/prometheus-remediation/assets/25551553/007e3ad2-418f-4794-80e9-b94415f5eab5)

2023-12-19 09:48 UTC, aantn requested changes
Very nice. Some comments and requests for small fixes.

2023-12-19 09:48 UTC, aantn commented on prometheus_remediation/job_runner.py
> +    env_var: Optional[List[EnvVar]] = None
Should be `env_vars` (plural)

2023-12-19 09:48 UTC, aantn commented on prometheus_remediation/job_runner.py
> +        except Exception as e:
You might swallow other exceptions (not just the one you are looking for)
Verify it is the right exception and rethrow it if it isn't the exception you are looking for.

See an example of how to do this here - https://stackoverflow.com/a/13531310/495995

2023-12-19 09:48 UTC, aantn commented on prometheus_remediation/job_runner.py
> +            print(f"Timed out running {job_name} for alert {event.alert_name}")
Use `logging.warning` not `print`.

Also, you're duplicating the string here and below. Make one copy, then log it and add it to the markdown block.

E.g:

```
err = f"...."
logging.warning(err)
event.add_enrichment([MarkdownBlock(err)])
```

As they say, DRY (don't repeat yourself)

2023-12-20 13:59 UTC, pavangudiwada commented
New alert
![image](https://github.com/robusta-dev/prometheus-remediation/assets/25551553/1dade905-d7df-4018-8f20-fc2260f9400a)

2023-12-21 13:29 UTC, aantn requested changes
Left some minor comments. Also please update the readme.

Finally, can you share details on how you tested this? (E.g. did you test the case where the job succeeds + the case where it fails + the case where it times out?)

2023-12-21 13:29 UTC, aantn commented on prometheus_remediation/job_runner.py
> +        info_messages.append(f"Created Job from alert: *{job_name}*.")
Can you make the "Create Job from alert" bold and the job itself not bold. (That will better match the style in the rest of the Slack message.)

2023-12-21 13:29 UTC, aantn commented on prometheus_remediation/job_runner.py
> +                warning_msg = f"Action Job stopped due to Exception {e}"
Can you rephrase as "Error running Job: {e}"

2023-12-21 13:29 UTC, aantn commented on prometheus_remediation/job_runner.py
> +                logging.warning(f"Action Job {job_name} - {err_str}")
Can you rephrase as "Failed to fetch Job result: {err_str}"

2023-12-22 13:14 UTC, aantn commented on README.md
> +      alert_name: KubeJobFailed
Can we use an alert that is *not* job-related. It's a little confusing that we're running a Job as a result but also triggering this on a failed job. Best to change the trigger and keep everything clear with one use of jobs here (the real one)

2023-12-22 13:14 UTC, aantn approved these changes
Approved, with one request for change.

2023-12-24 03:43 UTC, merged